// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnPQpKyZmW0wWpTkaD-k3fTrdQqUSWPXg',
    appId: '1:450284388918:web:a7437a278900dcb5184e97',
    messagingSenderId: '450284388918',
    projectId: 'po2023-5ad74',
    authDomain: 'po2023-5ad74.firebaseapp.com',
    storageBucket: 'po2023-5ad74.appspot.com',
    measurementId: 'G-JG4YG6RFKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFEf3TWnHNcbGOBcJSZY6oEO4qcxOw8LQ',
    appId: '1:450284388918:android:186a9b5c3de4d711184e97',
    messagingSenderId: '450284388918',
    projectId: 'po2023-5ad74',
    storageBucket: 'po2023-5ad74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFwUt3TcOK4UiDxSlMLSv-DDF24vMRsI0',
    appId: '1:450284388918:ios:245365bc25ee5166184e97',
    messagingSenderId: '450284388918',
    projectId: 'po2023-5ad74',
    storageBucket: 'po2023-5ad74.appspot.com',
    iosClientId: '450284388918-rth8rhkcadu040o1u8db48d8p4p2rl39.apps.googleusercontent.com',
    iosBundleId: 'com.bensonarafat.po2023',
  );
}
